[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "playground-core"
version = "0.1.0"
description = "Core ML pipeline and experiment tracking for Playground"
authors = [{name = "Playground Team"}]
requires-python = ">=3.11"
dependencies = [
    "sqlmodel>=0.0.8",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "scikit-learn>=1.3.0",
    "pyyaml>=6.0",
    "python-multipart>=0.0.5",
    "typer>=0.9.0"
]

[project.optional-dependencies]
dev = ["pytest>=7.0.0", "black>=23.0.0", "isort>=5.12.0", "mypy>=1.0.0"]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
